import "./globals.css";
import type { Metadata } from "next";
import AppWalletProvider from "@/components/AppWalletProvider";
import AppBarComponent from "@/components/AppBar";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config";
import AppKitProvider from "@/context";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body>
        <AppKitProvider initialState={initialState}>
          <AppWalletProvider>
            <main className="relative">
              <AppBarComponent />
              <div>{children}</div>
            </main>
          </AppWalletProvider>
        </AppKitProvider>
      </body>
    </html>
  );
}
